networks:
  scopeviewer-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: scopeviewer-redis
    networks:
      - scopeviewer-network

  deepzoom:
    image: scopeviewer-deepzoom:latest
    container_name: scopeviewer-deepzoom
    build:
      context: .
      dockerfile: ./deepzoom/Dockerfile
    ports:
      - "10010:9010"
    depends_on:
      - redis
    networks:
      - scopeviewer-network
    volumes:
      - ${SLIDES_DIR}:/app/slides
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: .
      dockerfile: ./iviewer-remoteurl/Dockerfile
    container_name: scopeviewer-frontend
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
    #   - ./iviewer-remoteurl:/app:delegated      # mount your source code
    #   - /app/node_modules              # anonymous volume hiding host modules
        - ./slides.json:/app/public/slides.json:ro
        - ./smp_data:/app/public/smp_data:ro
    depends_on:
      - deepzoom
    networks:
      - scopeviewer-network